name: 跃动

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # UTC时间 +8 北京
  watch:
    types: started
  repository_dispatch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/sunshine-yckx/JavaScript.git ~/JavaScript
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/JavaScript
          git checkout master
          npm install
      - name: '运行 【yuedon】'
        run: |
          cd ~/JavaScript
          node Task/yuedongzu.js
        env:
          TZ: Asia/shanghai
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          YDZ_yuedongzuTOKEN: ${{ secrets.YDZ_yuedongzuTOKEN }}
          YDZ_CASH: ${{ secrets.YDZ_CASH }}
